### ISSUE TITLE
Support for  pre compilation of expression

### ISSUE THREAD

**Issue by goodfella1408** [TomFrost/Jexl#29]
Is there a way I can pre compile an expression to save time during evaluation ?

**Comment by TomFrost** [comment]
Not yet, but this is a frequently requested feature that is likely to make it into the codebase!

**Comment by technicallyfeasible** [comment]
Over 2 years have passed since the original request. Is this still going to appear as a feature? I am looking for a parser to use in a speed sensitive setting and I like Jexl but wouldn't be able to use it without precompilation.

**Comment by TomFrost** [comment]
@technicallyfeasible It is, right now :) https://github.com/TomFrost/Jexl/pull/63

Quick overview:

```javascript
const myExpression = jexl.expr`5 + foo`
const ten = myExpression.evalSync({ foo: 5 }) // Expression gets compiled here
const fifteen = myExpression.evalSync({ foo: 10 }) // No compilation here
const twenty = myExpression.evalSync({ foo: 15 }) // None here either
```

Or if you're not a fan of tagged templates, or want full control over when compilation happens:

```javascript
const myExpression = jexl.compile(`5 + foo`) // Expression gets compiled here
const ten = myExpression.evalSync({ foo: 5 }) // No compilation here
const fifteen = myExpression.evalSync({ foo: 10 }) // Nor here
const twenty = myExpression.evalSync({ foo: 15 }) // None here either
```

Does this fit your use case?

**Comment by technicallyfeasible** [comment]
that look like it will work. thanks and good work 👍
