### ISSUE TITLE
cannot match variable starting with $

### ISSUE THREAD

**Issue by chaoyangnz** [TomFrost/Jexl#37]
```javascript
var jexl = require('jexl')

var context = {
    $a: 1
}
jexl.eval('$a', context)
```

`$a` is a legal variable name in Javascript.

I found it is the problem of delimiter regex.

Could you fix it? Thx

**Comment by johannesschobel** [comment]
any news on this? stumbled upon the same problem ;)

**Comment by TomFrost** [comment]
Fix merged to master!
