### ISSUE TITLE
Synchronous Jexl

### ISSUE THREAD

**Issue by kyyash** [TomFrost/Jexl#40]
Is there anyway I can use Jexl synchronously ?

**Comment by TomFrost** [comment]
At this point, no. In order for Jexl to support asynchronous operations at all, the entire library must be asynchronous.

I'm considering creating a synchronous mode in v2.0 as this is a frequent request. If that's enabled, Jexl will inject its own dummy Promise interface that runs synchronously, but you the user would have to give up any support for async operations in your expressions. Would you be interested in that?

**Comment by danrot** [comment]
I would be definitely interested in that! My use case is quite similar to the ones in your README (simply checking some values of a predefined object), and having async operations makes that unnecessary complicated (for this specific use case).

**Comment by Charuru** [comment]
Yes please sync mode!

**Comment by GaborTorma** [comment]
> This exists: https://www.npmjs.com/package/jexl-sync but I have no idea how to use it as `var jexl = require('Jexl');` no longer works.

You can use: var jexl = require(4);
You need the modify the js file in two place:
1. remove the ) sing from first line 408. char
2. replace the first ( sing from the first line to require=

your first line in jexl-sync-master\dist\jexl-sync.min.js the following:
`require=function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s}({1:[function(require,module,exports){`

**Comment by TomFrost** [comment]
Jexl v2 has been released without support for a synchronous mode (yet). I'm still hesitant to create such a parallel code path when it's easier than ever to run asynchronous code, but if anyone has a strong use case for this, I'd really love to hear more about it. In what cases do you need Jexl's functionality that prevent you from using an async API?

**Comment by TomFrost** [comment]
After much deliberation on implementation (See #46 for most recent discussion, #48 for final solution), synchronous support for Jexl has been released! 🎉 

After upgrading to version 2.1.0, you can call `jexl.evalSync` with the same arguments you'd normally pass to `eval`, but get a synchronous response. Enjoy, and please let me know if you run into any issues that the tests didn't catch.
