### ISSUE TITLE
compare 

### ISSUE THREAD

**Issue by k2s** [TomFrost/Jexl#47]
I believe this happend due to StandardJS suggestions.

version 1.1.4 was comparing string variables and number variables with `==` and `!=`
* `'2'==2` is true
* `'2'<=2` is true
* `'2'!=2` is false
* `'2'!=3` is true

version 2.0.1 breaks this by using `===` and `!==`
* `'2'==2` is false
* `'2'<=2` is true
* `'2'!=2` is true
* `'2'!=3` is true

When looking at how ``'2'<=2` is true` works you should revert back to use `==` and `!=`.

**Comment by TomFrost** [comment]
This is fixed in Jexl 2.0.2, published minutes ago.
