### ISSUE TITLE
Add an ES5 build

### ISSUE THREAD

**Issue by czosel** [TomFrost/Jexl#57]
Hi @TomFrost 

I've been running into some issues with running Jexl 2.0 in older browsers that don't support ES6 yet (specifically IE 11). Many libraries are publishing transpiled (and often also bundled) code to npm. Would you be interested in providing something like that for Jexl as well?

I might be able to open a PR for this, but I figured I'd ask first if you're interested at all :wink:

**Comment by akshaygolash** [comment]
@czosel - I am facing the same issue here, are you planning to create a PR?

**Comment by czosel** [comment]
Hi @akshaygolash - I'm not planning on creating a PR for this right now, because I solved the issue differently already. As you can see, this issue is already quite old. I think I'm gonna go ahead and create a issue that asks directly if @TomFrost would accept help with the maintenance of this library - I think Jexl is a great library and it would be a pity if simple things like this issue stop people from using it.

**Comment by akshaygolash** [comment]
@czosel - I agree with you 100%, Thanks for replying. Do you mind to share the approach you used to fix the issue?

The issue for my project is I am using Angular 9, and angular CLI expects all libraries to provide es5 build, and hence it is breaking in IE 11. 

Any help is appreciated!

**Comment by czosel** [comment]
We're using Jexl with Ember.js, and the issue was fixed in the framework itself (ember-auto-import transpiles dependencies automatically, https://github.com/ef4/ember-auto-import/issues/41). Sorry I can't be of more help :wink:

**Comment by akshaygolash** [comment]
Oh, I see, Thank you for your input. Much appreciated.

**Comment by akshaygolash** [comment]
Thanks @TomFrost  for your prompt response, Any idea what's the ETA for this enhancement?
And thanks again for this awesome package!

**Comment by TomFrost** [comment]
Hi @akshaygolash! No promises, but I'm hoping to cut a release this week. If all goes well, I'll have this in it.

**Comment by akshaygolash** [comment]
Awesome, thanks! Much appreciated.

**Comment by malka-ch** [comment]
Any updates?

**Comment by daniele-pecora** [comment]
Exactly what I need.
Would like to see the xorrespondibg pull request coming up soon 😀

**Comment by kawazoe** [comment]
While on the subject of builds, I would love to see a more versatile module format like UMD or just plain es6 modules without the CommonJS stuff in the way. This would be great for people using WebPack and Rollup since we could get tree-shaking working with this library.

**Comment by daniele-pecora** [comment]
@TomFrost Is this already part of any release now?

**Comment by TomFrost** [comment]
Hi everyone! I've been racing to try to complete the port to Typescript, as that will have to be compiled anyway. This isn't out yet, but is being actively worked on. If my timeline drags on, I'll release with @czosel's PR to tide folks over.

**Comment by czosel** [comment]
Hi @TomFrost, any updates on the typescript port? Might be worth sharing even something incomplete, to allow people to contribute?

**Comment by TomFrost** [comment]
Still tinkering on the Typescript side of things-- but a release is long overdue, so many thanks to @czosel's PR to add the ES5 build! That is now released in 2.3.0.

**Comment by czosel** [comment]
Awesome, thanks @TomFrost! :tada:

**Comment by TomFrost** [comment]
Nonono, thank _you_! 😉
