### ISSUE TITLE
escape dash

### ISSUE THREAD

**Issue by gunzip** [TomFrost/Jexl#58]
hi. is there any way to escape the dash (minus sign) character ?

```
jexl
  .eval('foo-bar == "foobar"', {
    "foo-bar": "foobar"
  })
  .then(console.log)
  .catch(console.error);

```

results `false`

**Comment by TomFrost** [comment]
Jexl is very similar to Javascript in that top-level variables in the context cannot contain dashes, start with a number, etc. But it's _also_ similar to javascript in that, if it's not at the top level, you can quote it:

```javascript
const context = { baz: { 'foo-bar': 'foobar' } }
const res = jexl.evalSync('baz["foo-bar"] == "foobar"', context)
console.log(res) // true
```

Hope this helps!

**Comment by TomFrost** [comment]
Closing until this need is articulated again :)
