### ISSUE TITLE
Support for accented letters in identifiers

### ISSUE THREAD

**Issue by heharkon** [TomFrost/Jexl#67]
Hi! I have the need for  "non-standard"  accented letters for the identifiers. Would it be possible to include a support for those as well?

I tried it out by extending the regexps for the identifiers and is seems to work. I'll make a pull request for you to consider that.

Thanks,
Henrik.

**Comment by heharkon** [comment]
The PR:
https://github.com/TomFrost/Jexl/pull/68

**Comment by TomFrost** [comment]
Merged! Thanks again Henrik :)
