### ISSUE TITLE
Support for referencing individual properties in a collection

### ISSUE THREAD

**Issue by austinkelleher** [TomFrost/Jexl#71]
This may already be supported, but if so, I couldn't find the syntax in the documentation. Currently, Jexl supports filtering using the `data[.name == 'Austin'].id` syntax. I'd like to be able to basically `map` an array, so that we can return a subset of properties.

Here are two examples of what I'm trying to accomplish:

Sample internal `map` functionality:

```js
const jexl = require('jexl');

// It would be great if this would return:
// [{ properties: { id: "abc" } }, { properties: { id: "def" } }]
const result = jexl.evalSync("data[.properties]", {
  data: [
    {
     name: 'John',
      properties: {
        id: 'abc'
      }
    },
    {
      name: 'Jane',
      properties: {
        id: 'def'
      }
    }
  ]
});
```

Sample mapping of sub properties:

```js
const jexl = require('jexl');

// [{ id: "abc" }, { id: "def" }]
const result = jexl.evalSync("data[.properties.id]", {
  data: [
    {
     name: 'John',
      properties: {
        id: 'abc'
      }
    },
    {
      name: 'Jane',
      properties: {
        id: 'def'
      }
    }
  ]
});
```

Thoughts @TomFrost?

**Comment by TomFrost** [comment]
This is super slick. I think this is probably better addressed by a transform rather than a change to the expression language, though, simply because others' use cases are likely to vary a lot on this. I'll 100% reconsider that if this gets overwhelming support!

Something like:

```javascript
jexl.addTransform('mapTo', (collection, prop) => collection.map(elem => elem[prop]))
jexl.evalSync("data|mapTo('properties')", context)
```
