### ISSUE TITLE
Interactive Jexl playground

### ISSUE THREAD

**Issue by czosel** [TomFrost/Jexl#80]
Hi @TomFrost,

I made a little interactive playground for Jexl: https://czosel.github.io/jexl-playground/ 
If you find it useful, I'd be happy to discuss how to move forward with it, for example by mentioning it in the docs, or even moving it to this repository?

It's implemented in Ember.js, you can find the code here: https://github.com/czosel/jexl-playground

**Comment by TomFrost** [comment]
This is SUPER cool -- thank you! I'll definitely line this up for the README.

**Comment by cunneen** [comment]
Just a quick note, I use npm's runkit integration as a playground for all sorts of npm packages. Jexl is one. It's not as jexl-specific as yours but you can also combine it with almost any other npm package (e.g. lodash) interactively.

https://npm.runkit.com/jexl

**Comment by czosel** [comment]
@TomFrost Awesome! :tada:

@cunneen I didn't know about runkit, thanks for the pointer!
